/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportscard;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author raian
 */
public class frstinningsscore extends javax.swing.JFrame {

    /**
     * Creates new form BallbyBall
     */
    String matchID;
    int run =0;
    int ball_no = 0;
    int wkt =0;
    int maxW ;
    int maxO;
    int ty;
    Database db = new Database();
    public frstinningsscore() throws SQLException {
        initComponents();
        midLabel.setText("hudai");
        maxO = 3;
        maxW = 10;
        cRunLabel.setText("0");
        wicketLabel.setText("0");
        overLabel.setText("0.0");
        
    }
    public frstinningsscore(String givenID,String _ht,String _at,int maxWkt,int maxover,int type) throws SQLException
    {
        initComponents();
        this.matchID = givenID;
        this.maxW = maxWkt;
        this.maxO = maxover;
        this.ty = type;
        midLabel.setText(givenID);
        cRunLabel.setText("0");
        wicketLabel.setText("0");
        overLabel.setText("0.0");
        if(ty==0)
        {
            tName.setText(db.selectHomeTeamName(matchID));
            
        }
        else
        {
            tName.setText(db.selectAwayTeamName(matchID));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        midLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inningsLabel = new javax.swing.JLabel();
        tName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cRunLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        wicketLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        overLabel = new javax.swing.JLabel();
        legalButton = new javax.swing.JRadioButton();
        illegalButton = new javax.swing.JRadioButton();
        dismissalButton = new javax.swing.JRadioButton();
        runBox = new javax.swing.JComboBox<>();
        dismissalBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        wide = new javax.swing.JRadioButton();
        noball = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jLabel1.setText("Match ID");

        midLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jLabel2.setText("Innings");

        inningsLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        inningsLabel.setText("first");

        tName.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        tName.setText("team 1");

        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jLabel5.setText("Run");

        cRunLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jLabel6.setText("Wicket");

        wicketLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jLabel7.setText("Over");

        overLabel.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N

        legalButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        legalButton.setText("Legal Delivery");
        legalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legalButtonActionPerformed(evt);
            }
        });

        illegalButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        illegalButton.setText("NO / WIDE DELIVERY");
        illegalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illegalButtonActionPerformed(evt);
            }
        });

        dismissalButton.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        dismissalButton.setText("Dismissal");

        runBox.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        runBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 RUNs", "1 RUN", "2 RUNs", "3 RUNs", "4 RUNs", "5 RUNs", "6 RUNs", "7 RUNs" }));

        dismissalBox.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        dismissalBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOWLED", "LEG BEFORE", "CAUGHT", "RUN-OUT", "OTHERS" }));

        jButton2.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        wide.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        wide.setText("Wide");
        wide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wideActionPerformed(evt);
            }
        });

        noball.setFont(new java.awt.Font("Felix Titling", 1, 12)); // NOI18N
        noball.setText("No Ball");
        noball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noballActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Felix Titling", 0, 12)); // NOI18N
        jButton3.setText("Reset Selection");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(legalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(illegalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dismissalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noball))
                            .addComponent(runBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dismissalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(midLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cRunLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wicketLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(overLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inningsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inningsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addComponent(cRunLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(wicketLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legalButton)
                    .addComponent(runBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(illegalButton)
                    .addComponent(wide)
                    .addComponent(noball))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dismissalButton)
                    .addComponent(dismissalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void illegalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illegalButtonActionPerformed
        // TODO add your handling code here:
        if(legalButton.isSelected())    legalButton.setSelected(false);
    }//GEN-LAST:event_illegalButtonActionPerformed

    private void legalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legalButtonActionPerformed
        // TODO add your handling code here:
        if(illegalButton.isSelected())  illegalButton.setSelected(false);
    }//GEN-LAST:event_legalButtonActionPerformed

    
    private void wideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wideActionPerformed
        // TODO add your handling code here:
        if(!illegalButton.isSelected()) wide.setSelected(false);
        if(noball.isSelected())     noball.setSelected(false);
    }//GEN-LAST:event_wideActionPerformed

    private void noballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noballActionPerformed
        // TODO add your handling code here:
        if(!illegalButton.isSelected()) noball.setSelected(false);
        if(wide.isSelected())       wide.setSelected(false);
    }//GEN-LAST:event_noballActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        legalButton.setSelected(false);
        illegalButton.setSelected(false);
        wide.setSelected(false);
        noball.setSelected(false);
        dismissalButton.setSelected(false);
        runBox.setSelectedIndex(0);
        dismissalBox.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
        if(legalButton.isSelected() || illegalButton.isSelected())
        {
            if(illegalButton.isSelected() && flag)
            {
                if(wide.isSelected() || noball.isSelected() && flag)
                {
                    flag = true;
                }
                else flag = false;
                if(dismissalButton.isSelected() && flag)
                {
                    if(dismissalBox.getSelectedIndex() == 3)    flag = true;
                    else                                        flag = false;
                }  
            }
            if(legalButton.isSelected() && dismissalButton.isSelected() && flag)
            {
                
                if( (dismissalBox.getSelectedIndex() < 3) && (runBox.getSelectedIndex() != 0) ) flag = false;
                else flag =true;
            }
            
        }
        else flag = false;
        if(flag == false)   
        {
            JOptionPane.showMessageDialog(rootPane, "Score input is not correct");
            
        }
        else
        {
            int ind = runBox.getSelectedIndex();
            int cr = 0;
            switch(ind){
                case 0:
                    cr = 0;
                     break;
                case 1:
                    cr = 1;
                    break;
                case 2:
                    cr = 2;
                    break;
                case 3:
                    cr = 3;
                    break;
                case 4:
                    cr = 4;
                    break;
                case 5:
                    cr = 5;
                    break;
                case 6:
                    cr = 6;
                    break;
                default:
                    cr = 7;
        }
            
                
        if(legalButton.isSelected())
        {
           if(dismissalButton.isSelected())
           {
               wkt = wkt + 1;
               if(wkt >= maxW)
               {
                   JOptionPane.showMessageDialog(rootPane,"Innings over");
                   secondInnings obj;
                   
                   try {
                       obj = new secondInnings(matchID,maxW,maxO,run,ty);
                       obj.setVisible(true);
                    dispose();
                   } catch (SQLException ex) {
                       Logger.getLogger(frstinningsscore.class.getName()).log(Level.SEVERE, null, ex);
                   }
                    
                   // go to next innings
               }
           }
           run = run + cr;
           ball_no = ball_no + 1;
           if(maxO*6 <= ball_no)    
           {
               JOptionPane.showMessageDialog(rootPane,"Innings over");
               secondInnings obj; 
               try {
                   obj = new secondInnings(matchID,maxW,maxO,run,this.ty);
                   obj.setVisible(true);
                  dispose();
               } catch (SQLException ex) {
                   Logger.getLogger(frstinningsscore.class.getName()).log(Level.SEVERE, null, ex);
               }
               
                // go to next innings
           }
        }
        else if(illegalButton.isSelected())
        {
            run = run + cr;
            if(wide.isSelected() || noball.isSelected())
            {
                run = run + 1;
            }
            if(dismissalButton.isSelected())
            {
                wkt = wkt + 1;
                if(wkt >= maxW)
                {
                    JOptionPane.showMessageDialog(rootPane,"Innings over");
                    JOptionPane.showMessageDialog(rootPane,"2nd Innings Starting");
                    secondInnings obj; 
                    try {
                        obj = new secondInnings(matchID,maxW,maxO,run,ty);
                        obj.setVisible(true);
                    dispose();
                    } catch (SQLException ex) {
                        Logger.getLogger(frstinningsscore.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        }
        cRunLabel.setText(Integer.toString(run));
        wicketLabel.setText(Integer.toString(wkt));
        String oo = Integer.toString(ball_no/6);
        oo = oo + "." + Integer.toString(ball_no%6);
        overLabel.setText(oo);
        
        legalButton.setSelected(false);
        illegalButton.setSelected(false);
        wide.setSelected(false);
        noball.setSelected(false);
        dismissalButton.setSelected(false);
        runBox.setSelectedIndex(0);
        dismissalBox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frstinningsscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frstinningsscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frstinningsscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frstinningsscore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frstinningsscore().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frstinningsscore.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cRunLabel;
    private javax.swing.JComboBox<String> dismissalBox;
    private javax.swing.JRadioButton dismissalButton;
    private javax.swing.JRadioButton illegalButton;
    private javax.swing.JLabel inningsLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton legalButton;
    private javax.swing.JLabel midLabel;
    private javax.swing.JRadioButton noball;
    private javax.swing.JLabel overLabel;
    private javax.swing.JComboBox<String> runBox;
    private javax.swing.JLabel tName;
    private javax.swing.JLabel wicketLabel;
    private javax.swing.JRadioButton wide;
    // End of variables declaration//GEN-END:variables
}
